version: '2'
services:
  mssql:
    image: ericskang/unittestdb:latest
    container_name: mssql
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "SqlDevOps2017"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
  mssql-cli:
    image: ericskang/sqltools:cli-insider
    container_name: mssql-cli
    command: ["tail", "-f", "/dev/null"]