FROM sqltools-python-base:latest
RUN pip install mssql-cli mssql-scripter

# FROM ubuntu:latest
# #FROM python:3-slim-stretch
# RUN apt-get update && apt-get install -y \ 
#     libunwind8 \
#     python python-pip libicu55 \
#     libicu57 libssl1.0.2 \
#     && rm -rf /var/lib/apt/lists/*
# RUN pip install --upgrade pip \
#     && pip install mssql-cli mssql-scripter